name: scp-sandbox
on:
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read
  
jobs:
  provision:
    name: terraform
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup-terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11
      - name: aws configure
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_SANDBOX }}
          aws-region: us-east-1
      - name: terraform init
        run: terraform init
      - name: terraform plan
        run: terraform plan -out=tfplan
      - name: Enforce module-only usage
        uses: open-policy-agent/conftest-action@v1
        with:
          policy: policy/
          files: tfplan.json
      - name: terraform apply
        run: terraform apply --auto-approve
